USE [MyCarService]

drop table [OperationStatus]
drop table [Transactions]
drop table [Details]
drop table [Operation]
drop table [Car]
drop table [Status]
drop table [Order]
drop table [Customer]
drop table [Employee]
drop table [ServiceType]
drop table [Department]
drop table [Job]
drop table [City]
drop table [Model]
drop table [Manufacturer]
drop table [State]